"""Public capability boundaries, independent of a user's private access state."""
CAPABILITIES = {
    "implemented": [
        "NMR raw-data API/teaching-archive acquisition, resumable questions, protected local credential panel, bounded ZIP/member validation and original file export",
        "Learn course/content discovery, verified downloads and document text reading",
        "Batch export of verified cached originals as MCP file attachments or a ZIP with manifest; host and cloud receipts remain separate",
        "Own EUCLID course marks and grades across loaded academic years; read-only, not an official transcript",
        "Supported MyEd/EUCLID student pages",
        "Personal Timetabler published-activity export, academic year/semester filters, concise weekly patterns and dated cache",
        "Course timetable PDF week/day cells with cross-page continuation and checksum-bound extraction cache",
        "One-call course material search, verified download and text reading; bounded folder traversal",
        "Loaded Learn activity updates and course inbox unread counters",
        "Structured official standard academic dates and Physics & Astronomy public events; explicit limited coverage",
        "Bounded official careers/events pages and MyCareerHub links",
        "Dated evidence, collections, tags, local tasks and draft plans",
        "Unified cached student agenda, linked local tasks and independent display timezone",
        "Ten-language service catalog, persistent preferences and per-call language overrides",
        "Portable MCP schemas, student tool profile and host configuration generator/merge installers",
        "Windows x64 setup ZIP with bundled Python, local bilingual wizard, checksum verification, configuration backups and runtime rollback",
        "15-tool daily profile with on-demand advanced operations; original student/full profiles remain compatible",
        "Official DeepSeek MCP bridge integration tested with a registration fixture",
        "Local ICS import/export; one private profile and connection per person",
    ],
    "not_implemented": [
        "NMR account creation, instrument operation/booking, experiment submission, spectral processing and automatic old-to-NOMAD migration",
        "Shared hosted multi-user service or one public Work connection for all users",
        "Coursework submission, marking, grade changes, attendance or bulk student administration",
        "Job applications, event booking, enrolment changes or message sending",
        "Complete exam/allocation coverage, scheduled background sync and remote calendar writes",
        "Full Learn message conversation bodies and university-wide Events App aggregation",
        "OCR, lecture-video transcription and all external/LTI providers",
    ],
    "out_of_scope": ["University email and mailbox workflows; handled through Outlook"],
    "unverified": [
        "Authenticated live NOMAD retrieval and real host NMR credential-panel acceptance; remote/mobile browsers cannot reach a campus computer's loopback panel",
        "Full Claude, WorkBuddy and DeepSeek model-turn acceptance; configuration/protocol/bridge tests are narrower",
        "Native-speaker review of every catalog translation and automatic translation of all source documents",
        "Teacher/staff-only Learn, EUCLID and administration pages",
        "Every feature of all directory entries; actual coverage is per user and service",
        "Live campus operation on macOS/Linux; Windows is the campus acceptance host",
    ],
    "sharing": "Share the source/install package. Each person supplies their own campus login and private MCP/Work connection.",
}
